name: paper
description: A state management pattern with tree-layout structured components.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ">=2.19.5 <3.0.0"

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  build_runner: ^2.4.10

dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter

  meta: ^1.8.0
  mockito: ^5.4.5
  mocktail: ^1.0.4
  leak_tracker_flutter_testing: ^3.0.8
