name: paper
version: 1.0.0
description: A state management pattern with tree-layout structured components.
homepage: https://www.paperflutter.com
repository: https://github.com/betta-dev-nest/paper

environment:
  sdk: ^2.19.5

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  mocktail: ^1.0.4

dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter

  meta: ^1.8.0
  mockito: ^5.4.5
  leak_tracker_flutter_testing: ^3.0.8
