// Mocks generated by Mockito 5.4.5 from annotations
// in paper/test/unit_tester.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:paper/src/interfaces/unit.dart' as _i4;

import 'unit_tester.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [AgentValidator].
///
/// See the documentation for Mockito's code generation for more information.
class MockAgentValidator extends _i1.Mock implements _i2.AgentValidator {
  @override
  _i3.Future<void> process(_i4.Agent<_i4.Paper>? agent, _i4.Paper? paper) =>
      (super.noSuchMethod(
        Invocation.method(#process, [agent, paper]),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<_i4.Paper?> report(_i4.Agent<_i4.Paper>? agent, Type? type) =>
      (super.noSuchMethod(
        Invocation.method(#report, [agent, type]),
        returnValue: _i3.Future<_i4.Paper?>.value(),
        returnValueForMissingStub: _i3.Future<_i4.Paper?>.value(),
      ) as _i3.Future<_i4.Paper?>);
}
